version: '3.9'

services:

# https://hub.docker.com/_/php
  app-php:
    labels:
      type: php
    image: localhost:5000/app-php:${APP_VERSION}
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10s
    ports:
      - '${PORT_PHP}:80'
    volumes:
      - type: volume
        source: data-php
        target: /var/www/html
    deploy:
      replicas: 5
    networks:
      - app-cakephp

# https://hub.docker.com/_/mysql
  db-mysql:
    labels:
      type: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    ports:
      - '${PORT_MYSQL}:3306'
    volumes:
      - type: volume
        source: data-mysql
        target: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
    networks:
      - app-cakephp
  
# https://hub.docker.com/_/redis
  db-redis:
    labels:
      type: redis
    image: redis:7.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    ports:
      - ${PORT_REDIS}:6379
    volumes:
      - type: volume
        source: data-redis
        target: /data
    command: redis-server --appendonly yes
    deploy:
      replicas: 1
    networks:
      - app-cakephp

# https://hub.docker.com/_/phpmyadmin
  dbclient-phpmyadmin:
    labels:
      type: phpmyadmin
    image: phpmyadmin:5.2.0-apache
    depends_on:
      - db-mysql
    environment:
      PMA_HOST: db-mysql
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10s
    ports:
      - '${PORT_PHPMYADMIN}:80'
    deploy:
      replicas: 1
    networks:
      - app-cakephp

# https://hub.docker.com/r/erikdubbelboer/phpredisadmin
  dbclient-phpredisadmin:
    labels:
      type: phpredisadmin
    image: erikdubbelboer/phpredisadmin:1.18
    depends_on:
      - db-redis
    environment:
      REDIS_1_HOST: db-redis
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10s
    ports:
      - '${PORT_PHPREDISADMIN}:80'
    deploy:
      replicas: 1
    networks:
      - app-cakephp

networks:
  app-cakephp:

volumes:
  data-php:
    name: php-data
  data-redis:
    name: redis-data
  data-mysql:
    name: mysql-data