version: '3.9'
services:

  # https://hub.docker.com/_/registry
  docker-registry:
    image: registry:2.8.1
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: data-registry
        target: /var/lib/registry

  # https://hub.docker.com/r/konradkleine/docker-registry-frontend
  docker-ui:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - docker-registry
    container_name: registry-ui
    restart: always
    ports:
      - 9003:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000

volumes:
  data-registry:
    driver: local
